### PR TITLE
resloves #99

### PR DESCRIPTION
**Pull request by bander-saeed94**
Resolves: error: Uncaught Error: Don't know how to parse column type: 1042

### CODE REVIEW

**Comment by bander-saeed94** [comment]
Anyone to merge this pull request

**Comment by hayd** [comment]
Awesome! Could you add a test for this case?

**Comment by bander-saeed94** [comment]
Hi @hayd , thanks for your response. I have updated the pull request. Yet I am not sure how to conduct the test locally.

**Comment by hayd** [comment]
Hmm, GitHub actions didn't trigger, I wonder why that would be! Thanks for adding the test, will merge soon.

**Comment by bander-saeed94** [comment]
Thanks

**Comment by hayd** [comment]
believe I've turned on actions on the repo (it seems like it was turned off when moving org).

tested locally and passing 👍 thank you!

**Pull request merged**
